### ISSUE TITLE
scrollspy overlaps "group" checkbox button

### ISSUE THREAD

**Issue by sgimeno** [adab1ts/www.pareudepararme.org#9]
On mobile versions or narrow screens the right navigation menu tooltips overlap with the form checkbox control causing a weird UX when filling the form from a mobile device.

<img width="406" alt="screen shot 2017-11-24 at 10 42 52" src="https://user-images.githubusercontent.com/946661/33204647-83c11604-d104-11e7-8068-a6b667150222.png">

**Comment by laklau** [comment]
#10
